version: "3.8"
services:
  django_app:
    build: .
    command:
      -python manage.py runserver 0.0.0.0:8123
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8123:8123
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/ver/lib/postgresgl/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
volumes:
  postgres_data:
